# Generated by Django 3.2.9 on 2023-06-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0004_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
