# Generated by Django 3.2.9 on 2023-06-14 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fd', '0002_auto_20230614_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixeddeposit',
            name='period',
        ),
    ]
